title: Process Mining 4 Sustainability Workshop
description: > # this means to ignore newlines until "baseurl:"
  Join us at PM4S 2025, the second international workshop on Process Mining for Sustainability, co-located with ICPM 2025 at UdelaR, Montevideo.
baseurl: /workshop # the subpath of your site, e.g. /blog
url: https://pm4s-ws.github.io # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/css/2024_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2024_pages', '_2025_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com
  - title: linkedin
    url: https://www.linkedin.com

# Build settings
markdown: kramdown
permalink: pretty